# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # Pods for TheApp

  target 'TheAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TheApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheApp-tvOS

  target 'TheApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
